### PR TITLE
Implementing a menu

### PR DESCRIPTION
**Pull request by OguleG**

### CODE REVIEW

**Comment by jptrzy** [comment]
There is a problem with resizing of the menu when changing the window resolution.

It must be fixed if you want to merge it.

**Comment by OguleG** [comment]
ok no problem

**Comment by jptrzy** [comment]
I can't go out of the settings menu and font is blurred.

**Comment by OguleG** [comment]
Everything is working fine so maybe you run a game from different scene (only run a game from start scene)

**Comment by jptrzy** [comment]
I don't think so.

Now, when I press escape or press resume button in the menu, it goes to the settings page, from which I can go back to the menu page.

And if I open the settings page by pressing the settings button, I can't go back from that to the menu page.

...also use the *res* and *assets* folders properly, don't just put all files to the main folder. 

image

**Pull request merged**
